name: Basic CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.1
      - name: Install dependencies
        run: Make install
      - name: Start Frontend
        run: Make dev-fe
      - name: Start Backend
        run: Make dev-be
