name: Basic CI

on:
  pull_request:
    branches: [ main, master ] # Runs PRs targeting these branches

jobs:
  test:
    runs-on: ubuntu-latest # The Host Machine (hardware)

    steps:
      # Download code into the container
      - name: Check out repository
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Setup Node with pnpm caching
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Clean install for pnpm; if lockfile needs to be updated, fail the build
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linting
        run: make lint

      # As generated/client is .gitignored, needed for tests (likely)
      # - name: Generate Database Client
      #   run: pnpm --filter @grit/backend exec prisma generate

      # - name: Run Tests
      #   run: make test
